import {StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import {FontSize, FontsStyle} from '../../utils/FontsStyle';
import GeneralStyle from '../../utils/GeneralStyle';
import SharedStyles from '../../utils/SharedStyles';

const sheet = StyleSheet.create({
  ...SharedStyles,
  container: {
    flex: 1,
    width: '100%',
  },
  svContainer: {
    padding: GeneralStyle.spacing.sm,
  },
  pinContainer: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingTop: GeneralStyle.spacing.xs,
    paddingBottom: GeneralStyle.spacing.sm,
    backgroundColor: Colors.ivory,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderSoft,
  },
  header: {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.sm,
  },
  headerText: {
    flex: 1,
  },
  title: {
    ...FontsStyle.menuTitle,
    fontSize: FontSize.title,
    color: Colors.darkGreen,
  },
  subtitle: {
    ...FontsStyle.text,
    color: Colors.slate,
    marginTop: GeneralStyle.spacing.xs,
  },
  countBadge: {
    minWidth: GeneralStyle.size.badge,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.goldWash,
  },
  countText: {
    ...FontsStyle.menuTitle,
    fontSize: FontSize.title,
    color: Colors.color1,
    textAlign: 'center',
  },
  countLabel: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  calendarButton: {
    marginBottom: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  calendarButtonText: {
    ...FontsStyle.text,
    color: Colors.ivory,
  },
  sectionHeader: {
    marginTop: GeneralStyle.spacing.md,
    marginBottom: GeneralStyle.spacing.sm,
  },
  sectionTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
  },
  card: {
    marginBottom: GeneralStyle.spacing.sm,
  },
  aiScoreBar: {
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.goldWash,
  },
  aiScoreBadge: {
    minWidth: 70,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.sm,
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.white,
  },
  aiScoreValue: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.title,
    textAlign: 'center',
  },
  aiScoreLabel: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
  aiReasons: {
    flex: 1,
  },
  aiReasonsTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
  },
  aiReasonsText: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: FontSize.caption,
    marginTop: 2,
  },
  meetingPanel: {
    gap: GeneralStyle.spacing.sm,
    marginTop: GeneralStyle.spacing.sm,
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.ivory,
  },
  fieldGroup: {
    gap: 5,
  },
  fieldLabel: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.small,
  },
  meetingStatusRow: {
    gap: GeneralStyle.spacing.xs,
  },
  statusButton: {
    flex: 1,
    minHeight: GeneralStyle.size.control,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    paddingVertical: GeneralStyle.spacing.xs,
    backgroundColor: Colors.ivory,
    borderColor: Colors.borderSoft,
    borderWidth: 1,
    borderRadius: GeneralStyle.radius.md,
    shadowOpacity: 0,
    elevation: 0,
  },
  statusButtonActive: {
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  statusButtonText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  statusButtonTextActive: {
    color: Colors.ivory,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.color1,
  },
  meetingField: {
    minHeight: GeneralStyle.size.control,
    alignItems: 'center',
    gap: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.xs,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
  },
  meetingIconBox: {
    width: GeneralStyle.size.iconMd,
    height: GeneralStyle.size.iconMd,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.color1Light,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.goldSoft,
  },
  meetingFieldText: {
    ...FontsStyle.text,
    flex: 1,
    color: Colors.darkGreen,
  },
  meetingTimeText: {
    textAlign: 'right',
    writingDirection: 'ltr',
  },
  meetingInput: {
    ...FontsStyle.text,
    flex: 1,
    minHeight: GeneralStyle.size.iconLarge,
    color: Colors.darkGreen,
    paddingVertical: 0,
  },
  selectFieldContainer: {
    width: '100%',
  },
  invalidMeetingField: {
    borderColor: Colors.danger,
    backgroundColor: Colors.dangerSoft,
  },
  validationText: {
    ...FontsStyle.text,
    color: Colors.danger,
    fontSize: FontSize.caption,
    textAlign: 'right',
  },
  availableMessage: {
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.champagne,
  },
  availableMessageText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.md,
    backgroundColor: Colors.overlay,
  },
  meetingModalScroll: {
    maxHeight: '92%',
  },
  meetingModalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  meetingModal: {
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.sm,
    borderRadius: GeneralStyle.radius.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.ivory,
    ...Colors.Shadow,
  },
  modalHeader: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  modalTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.title,
  },
  modalCloseButton: {
    width: GeneralStyle.size.icon,
    height: GeneralStyle.size.icon,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.white,
  },
  modalCloseText: {
    ...FontsStyle.text,
    ...SharedStyles.iconGlyphText,
    color: Colors.darkGreen,
  },
  modalSaveButton: {
    flex: 1,
    marginTop: 4,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  modalSaveText: {
    ...FontsStyle.text,
    color: Colors.ivory,
  },
  modalActions: {
    gap: GeneralStyle.spacing.sm,
  },
  modalCancelButton: {
    flex: 1,
    marginTop: 4,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.white,
    borderColor: Colors.borderSoft,
  },
  modalCancelText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  inlineTimePicker: {
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.xs,
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.white,
  },
  timePickerValue: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.display,
    textAlign: 'center',
    writingDirection: 'ltr',
  },
  timePickerColumns: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  timePickerColumn: {
    flex: 1,
    alignItems: 'center',
    gap: GeneralStyle.spacing.xs,
  },
  timePickerSeparator: {
    width: 1,
    height: GeneralStyle.size.avatar,
    backgroundColor: Colors.borderSoft,
  },
  timePickerLabel: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'center',
  },
  timePickerButton: {
    width: GeneralStyle.size.control,
    height: GeneralStyle.size.icon,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.color1Light,
    backgroundColor: Colors.goldSoft,
  },
  timePickerButtonText: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    lineHeight: 28,
  },
  timePickerPart: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'center',
    writingDirection: 'ltr',
  },
  timePickerConfirmButton: {
    marginTop: GeneralStyle.spacing.xs,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
});

export const styles = sheet;
