import {StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import {FontsStyle} from '../../utils/FontsStyle';
import GeneralStyle from '../../utils/GeneralStyle';

const sheet = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
  },
  svContainer: {
    padding: GeneralStyle.spacing.sm,
  },
  pinContainer: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingTop: GeneralStyle.spacing.xs,
    paddingBottom: GeneralStyle.spacing.sm,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderSoft,
  },
  header: {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.sm,
  },
  headerText: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
  },
  rowReverse: {
    flexDirection: 'row-reverse',
  },
  alignStart: {
    alignItems: 'flex-start',
  },
  alignEnd: {
    alignItems: 'flex-end',
  },
  textLeft: {
    textAlign: 'left',
  },
  textRight: {
    textAlign: 'right',
  },
  title: {
    ...FontsStyle.menuTitle,
    fontSize: 20,
    color: Colors.darkGreen,
  },
  subtitle: {
    ...FontsStyle.text,
    color: Colors.slate,
    marginTop: GeneralStyle.spacing.xs,
  },
  countBadge: {
    minWidth: 64,
    alignItems: 'center',
    paddingVertical: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.champagne,
    borderTopWidth: 0,
    borderLeftWidth: 3,
    borderLeftColor: Colors.color1,
  },
  countText: {
    ...FontsStyle.menuTitle,
    fontSize: 20,
    color: Colors.color1,
  },
  countLabel: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: 12,
  },
  calendarButton: {
    marginBottom: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  calendarButtonText: {
    ...FontsStyle.text,
    color: Colors.ivory,
  },
  sectionHeader: {
    marginBottom: GeneralStyle.spacing.sm,
  },
  sectionTitle: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 18,
  },
  card: {
    marginBottom: GeneralStyle.spacing.sm,
  },
  aiScoreBar: {
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.goldWash,
  },
  aiScoreBadge: {
    minWidth: 70,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.sm,
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.surfaceElevated,
  },
  aiScoreValue: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: 20,
    textAlign: 'center',
  },
  aiScoreLabel: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: 11,
    textAlign: 'center',
  },
  aiReasons: {
    flex: 1,
  },
  aiReasonsTitle: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 15,
  },
  aiReasonsText: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: 12,
    marginTop: 2,
  },
  meetingPanel: {
    gap: GeneralStyle.spacing.sm,
    marginTop: GeneralStyle.spacing.sm,
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.ivory,
  },
  fieldGroup: {
    gap: 5,
  },
  fieldLabel: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 15,
  },
  meetingStatusRow: {
    gap: GeneralStyle.spacing.xs,
  },
  trackingPanel: {
    gap: GeneralStyle.spacing.xs,
    paddingVertical: GeneralStyle.spacing.xs,
  },
  statusButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    paddingVertical: GeneralStyle.spacing.xs,
    backgroundColor: Colors.ivory,
    borderColor: Colors.borderSoft,
    borderWidth: 1,
    borderRadius: GeneralStyle.radius.md,
    shadowOpacity: 0,
    elevation: 0,
  },
  statusButtonActive: {
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  statusButtonReadonly: {
    opacity: 0.75,
  },
  statusButtonText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  statusButtonTextActive: {
    color: Colors.ivory,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.color1,
  },
  meetingField: {
    minHeight: 44,
    alignItems: 'center',
    gap: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.xs,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  meetingIconBox: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.color1Light,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.goldSoft,
  },
  meetingFieldText: {
    ...FontsStyle.text,
    flex: 1,
    color: Colors.darkGreen,
  },
  meetingTimeText: {
    textAlign: 'right',
    writingDirection: 'ltr',
  },
  meetingInput: {
    ...FontsStyle.text,
    flex: 1,
    minHeight: 40,
    color: Colors.darkGreen,
    paddingVertical: 0,
  },
  selectFieldContainer: {
    width: '100%',
  },
  invalidMeetingField: {
    borderColor: '#DFA097',
    backgroundColor: '#FFF5F1',
  },
  validationText: {
    ...FontsStyle.text,
    color: '#9F4239',
    fontSize: 12,
    textAlign: 'right',
  },
  availableMessage: {
    padding: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.champagne,
  },
  availableMessageText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.md,
    backgroundColor: Colors.overlay,
  },
  meetingModalScroll: {
    maxHeight: '92%',
  },
  meetingModalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  meetingModal: {
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.sm,
    borderRadius: GeneralStyle.radius.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.ivory,
    ...Colors.Shadow,
  },
  modalHeader: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  modalTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: 20,
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.surfaceElevated,
  },
  modalCloseText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: 24,
    lineHeight: 28,
  },
  modalSaveButton: {
    marginTop: 4,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
  modalSaveText: {
    ...FontsStyle.text,
    color: Colors.ivory,
  },
  inlineTimePicker: {
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.xs,
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.surfaceElevated,
  },
  timePickerValue: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: 26,
    textAlign: 'center',
    writingDirection: 'ltr',
  },
  timePickerColumns: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  timePickerColumn: {
    flex: 1,
    alignItems: 'center',
    gap: GeneralStyle.spacing.xs,
  },
  timePickerSeparator: {
    width: 1,
    height: 88,
    backgroundColor: Colors.borderSoft,
  },
  timePickerLabel: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'center',
  },
  timePickerButton: {
    width: 44,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.color1Light,
    backgroundColor: Colors.goldSoft,
  },
  timePickerButtonText: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 24,
    lineHeight: 28,
  },
  timePickerPart: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: 24,
    textAlign: 'center',
    writingDirection: 'ltr',
  },
  timePickerConfirmButton: {
    marginTop: GeneralStyle.spacing.xs,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.darkGreen,
    borderColor: Colors.color1,
  },
});

export const styles = sheet;
