import {Dimensions, StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import GeneralStyle from '../../utils/GeneralStyle';
import {FontsStyle} from '../../utils/FontsStyle';

const {width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.appBg,
  },
  bgShapeOne: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 150,
    backgroundColor: Colors.ivory,
    borderBottomWidth: 1,
    borderBottomColor: Colors.line,
    opacity: 0.85,
  },
  bgShapeTwo: {
    position: 'absolute',
    width: width * 1.2,
    height: 82,
    top: 112,
    right: -width * 0.16,
    backgroundColor: Colors.goldWash,
    opacity: 0.9,
    transform: [{rotate: '-7deg'}],
  },
  slide: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    paddingTop: GeneralStyle.spacing.xl,
  },
  slideCard: {
    width: '100%',
    minHeight: 520,
    justifyContent: 'space-between',
    padding: GeneralStyle.spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderTopWidth: 3,
    borderTopColor: Colors.premiumLine,
    borderRadius: GeneralStyle.radius.lg,
    backgroundColor: Colors.surfaceElevated,
    ...Colors.Shadow,
  },
  eyebrow: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: 13,
    textAlign: 'center',
  },
  previewCard: {
    minHeight: 260,
    justifyContent: 'center',
    gap: GeneralStyle.spacing.md,
    padding: GeneralStyle.spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.ivory,
  },
  previewHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: GeneralStyle.spacing.md,
  },
  avatar: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: Colors.navyDeep,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
  },
  avatarText: {
    ...FontsStyle.menuTitle,
    color: Colors.white,
    fontSize: 26,
    textAlign: 'center',
  },
  previewTitleBlock: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 2,
  },
  previewName: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 22,
    textAlign: 'right',
  },
  previewMeta: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  infoGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: GeneralStyle.spacing.xs,
  },
  infoChip: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.xs,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.sm,
    backgroundColor: Colors.goldWash,
  },
  infoChipText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: 13,
  },
  profileLine: {
    height: 9,
    width: '100%',
    borderRadius: 999,
    backgroundColor: Colors.line,
  },
  profileLineShort: {
    width: '68%',
    alignSelf: 'flex-end',
  },
  preferenceRow: {
    minHeight: 58,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: GeneralStyle.spacing.sm,
    paddingHorizontal: GeneralStyle.spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  preferenceLabel: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  preferenceValue: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 18,
    textAlign: 'left',
  },
  matchScore: {
    alignSelf: 'center',
    width: 118,
    height: 118,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 59,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.goldWash,
  },
  matchScoreText: {
    ...FontsStyle.menuTitle,
    color: Colors.navyDeep,
    fontSize: 30,
    textAlign: 'center',
  },
  matchScoreLabel: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: 12,
    textAlign: 'center',
  },
  reasonRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  reasonDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: Colors.premiumLine,
  },
  reasonText: {
    ...FontsStyle.text,
    flex: 1,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  calendarTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  calendarDay: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 22,
  },
  calendarTime: {
    ...FontsStyle.menuTitle,
    color: Colors.goldDark,
    fontSize: 28,
  },
  meetingCard: {
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  meetingTitle: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  meetingMeta: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  statusPill: {
    alignSelf: 'flex-end',
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.xs,
    borderRadius: GeneralStyle.radius.sm,
    backgroundColor: Colors.successSoft,
  },
  statusPillText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: 13,
  },
  title: {
    ...FontsStyle.wizardTitle,
    color: Colors.darkGreen,
    fontSize: 27,
    textAlign: 'center',
  },
  subtitle: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.md,
    zIndex: 2,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.border,
    marginHorizontal: 5,
  },
  activeDot: {
    width: 26,
    backgroundColor: Colors.premiumLine,
  },
  buttonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 64,
    marginHorizontal: GeneralStyle.spacing.lg,
    marginBottom: GeneralStyle.spacing.xl,
    gap: GeneralStyle.spacing.sm,
  },
  skipButton: {
    minWidth: 64,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: GeneralStyle.spacing.sm,
  },
  skipText: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: 15,
    textAlign: 'center',
  },
  prevButton: {
    minWidth: 86,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  prevButtonText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: 15,
    textAlign: 'center',
  },
  nextButton: {
    minWidth: 104,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    paddingVertical: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.navyDeep,
  },
  nextButtonText: {
    ...FontsStyle.text,
    color: Colors.white,
    fontSize: 16,
    textAlign: 'center',
  },
});
