import {Dimensions, StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import GeneralStyle from '../../utils/GeneralStyle';
import {CardBorderStyle} from '../../utils/SharedStyles';
import {FontSize, FontsStyle} from '../../utils/FontsStyle';

const {width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.appBg,
  },
  bgShapeOne: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: 150,
    backgroundColor: Colors.ivory,
    borderBottomWidth: 1,
    borderBottomColor: Colors.line,
    opacity: 0.85,
  },
  bgShapeTwo: {
    position: 'absolute',
    width: width * 1.2,
    height: 82,
    top: 112,
    right: -width * 0.16,
    backgroundColor: Colors.goldWash,
    opacity: 0.9,
    transform: [{rotate: '-7deg'}],
  },
  slide: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    paddingTop: GeneralStyle.spacing.xl,
  },
  slideCard: {
    ...CardBorderStyle,
    width: '100%',
    minHeight: 520,
    justifyContent: 'space-between',
    padding: GeneralStyle.spacing.lg,
    backgroundColor: Colors.white,
    ...Colors.Shadow,
  },
  eyebrow: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
  previewCard: {
    ...CardBorderStyle,
    minHeight: 260,
    justifyContent: 'center',
    gap: GeneralStyle.spacing.md,
    padding: GeneralStyle.spacing.lg,
    backgroundColor: Colors.ivory,
  },
  previewHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: GeneralStyle.spacing.md,
  },
  avatar: {
    width: GeneralStyle.size.largeControl,
    height: GeneralStyle.size.largeControl,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: Colors.navyDeep,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
  },
  avatarText: {
    ...FontsStyle.menuTitle,
    color: Colors.white,
    fontSize: FontSize.display,
    textAlign: 'center',
  },
  previewTitleBlock: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 2,
  },
  previewName: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.heading,
    textAlign: 'right',
  },
  previewMeta: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  infoGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: GeneralStyle.spacing.xs,
  },
  infoChip: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingVertical: GeneralStyle.spacing.xs,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.sm,
    backgroundColor: Colors.goldWash,
  },
  infoChipText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: FontSize.caption,
  },
  profileLine: {
    height: 9,
    width: '100%',
    borderRadius: 999,
    backgroundColor: Colors.line,
  },
  profileLineShort: {
    width: '68%',
    alignSelf: 'flex-end',
  },
  preferenceRow: {
    minHeight: GeneralStyle.size.largeControl,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: GeneralStyle.spacing.sm,
    paddingHorizontal: GeneralStyle.spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
  },
  preferenceLabel: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  preferenceValue: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.large,
    textAlign: 'left',
  },
  matchScore: {
    alignSelf: 'center',
    width: GeneralStyle.size.media,
    height: GeneralStyle.size.media,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 59,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.goldWash,
  },
  matchScoreText: {
    ...FontsStyle.menuTitle,
    color: Colors.navyDeep,
    fontSize: FontSize.displayLarge,
    textAlign: 'center',
  },
  matchScoreLabel: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
  reasonRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  reasonDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: Colors.premiumLine,
  },
  reasonText: {
    ...FontsStyle.text,
    flex: 1,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  calendarTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  calendarDay: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.heading,
  },
  calendarTime: {
    ...FontsStyle.menuTitle,
    color: Colors.goldDark,
    fontSize: FontSize.display,
  },
  meetingCard: {
    ...CardBorderStyle,
    gap: GeneralStyle.spacing.xs,
    padding: GeneralStyle.spacing.md,
    backgroundColor: Colors.white,
  },
  meetingTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'right',
  },
  meetingMeta: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  statusPill: {
    alignSelf: 'flex-end',
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.xs,
    borderRadius: GeneralStyle.radius.sm,
    backgroundColor: Colors.successSoft,
  },
  statusPillText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: FontSize.caption,
  },
  ringPreviewStage: {
    minHeight: 126,
    justifyContent: 'center',
    padding: GeneralStyle.spacing.md,
  },
  ringCard: {
    ...CardBorderStyle,
    minHeight: GeneralStyle.size.avatar,
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.white,
  },
  ringCardName: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    textAlign: 'right',
  },
  ringCardMeta: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'right',
  },
  floatingRingButton: {
    position: 'absolute',
    left: GeneralStyle.spacing.lg,
    bottom: 0,
    width: GeneralStyle.size.badge,
    height: GeneralStyle.size.badge,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 31,
    backgroundColor: Colors.navyDeep,
    borderWidth: 2,
    borderColor: Colors.premiumLine,
    ...Colors.Shadow,
  },
  floatingRingInner: {
    width: GeneralStyle.size.icon,
    height: GeneralStyle.size.icon,
    borderRadius: 17,
    borderWidth: 5,
    borderColor: Colors.white,
  },
  ringActions: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  ringActionPill: {
    minWidth: GeneralStyle.size.avatar,
    alignItems: 'center',
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.xs,
    borderRadius: GeneralStyle.radius.sm,
    backgroundColor: Colors.goldWash,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
  },
  ringActionText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: FontSize.caption,
    textAlign: 'center',
  },
  ringPreviewNote: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: FontSize.caption,
    lineHeight: 20,
    textAlign: 'center',
  },
  title: {
    ...FontsStyle.wizardTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'center',
  },
  subtitle: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: FontSize.small,
    lineHeight: 23,
    textAlign: 'center',
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.md,
    zIndex: 2,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.border,
    marginHorizontal: 5,
  },
  activeDot: {
    width: 26,
    backgroundColor: Colors.premiumLine,
  },
  buttonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: GeneralStyle.size.badge,
    marginHorizontal: GeneralStyle.spacing.lg,
    marginBottom: GeneralStyle.spacing.xl,
    gap: GeneralStyle.spacing.sm,
  },
  skipButton: {
    minWidth: GeneralStyle.size.badge,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: GeneralStyle.spacing.sm,
  },
  skipText: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: FontSize.small,
    textAlign: 'center',
  },
  prevButton: {
    minWidth: GeneralStyle.size.avatar,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
  },
  prevButtonText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
    fontSize: FontSize.small,
    textAlign: 'center',
  },
  nextButton: {
    minWidth: GeneralStyle.size.label,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    paddingVertical: GeneralStyle.spacing.sm,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.navyDeep,
  },
  nextButtonText: {
    ...FontsStyle.text,
    color: Colors.white,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
});
