import { StyleSheet } from 'react-native';
import Colors from '../../utils/Colors';
import {FontsStyle} from '../../utils/FontsStyle';
import GeneralStyle from '../../utils/GeneralStyle';

export const styles = StyleSheet.create({
    headerStyle: {
        height: 92,
        backgroundColor: Colors.darkGreen,
    },
    drawerStyle: {
        width: '82%',
        backgroundColor: Colors.ivory,
        borderTopLeftRadius: GeneralStyle.radius.lg,
        borderBottomLeftRadius: GeneralStyle.radius.lg,
    },
    drawerContent: {
        flexGrow: 1,
        paddingTop: GeneralStyle.spacing.lg,
        paddingHorizontal: GeneralStyle.spacing.md,
        paddingBottom: GeneralStyle.spacing.xl,
        backgroundColor: Colors.ivory,
    },
    drawerHeader: {
        alignItems: 'center',
        paddingTop: GeneralStyle.spacing.md,
        paddingBottom: GeneralStyle.spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: Colors.line,
    },
    drawerLogo: {
        width: 62,
        height: 62,
        borderRadius: 31,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.goldWash,
        borderWidth: 1,
        borderColor: Colors.color1Light,
        marginBottom: GeneralStyle.spacing.sm,
    },
    drawerLogoText: {
        ...FontsStyle.textDecoration,
        color: Colors.goldDark,
        fontSize: 18,
    },
    drawerBrand: {
        ...FontsStyle.menuTitle,
        color: Colors.darkGreen,
        fontSize: 24,
        textAlign: 'center',
    },
    drawerSubtitle: {
        ...FontsStyle.text,
        color: Colors.slate,
        fontSize: 13,
        marginTop: 2,
        textAlign: 'center',
    },
    drawerProfileCard: {
        flexDirection: 'row-reverse',
        alignItems: 'center',
        gap: GeneralStyle.spacing.sm,
        paddingHorizontal: GeneralStyle.spacing.md,
        paddingVertical: GeneralStyle.spacing.md,
        marginTop: GeneralStyle.spacing.md,
        marginBottom: GeneralStyle.spacing.md,
        borderWidth: 1,
        borderColor: Colors.borderSoft,
        borderRadius: GeneralStyle.radius.md,
        backgroundColor: Colors.surfaceElevated,
    },
    profileAvatar: {
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.navyDeep,
        borderWidth: 1,
        borderColor: Colors.premiumLine,
    },
    profileAvatarText: {
        ...FontsStyle.textDecoration,
        color: Colors.white,
        fontSize: 18,
    },
    profileTextBlock: {
        flex: 1,
        alignItems: 'flex-end',
    },
    profileName: {
        ...FontsStyle.textDecoration,
        color: Colors.darkGreen,
        fontSize: 16,
    },
    profileRole: {
        ...FontsStyle.text,
        color: Colors.slate,
        fontSize: 12,
    },
    drawerSection: {
        gap: GeneralStyle.spacing.xs,
    },
    drawerItem: {
        minHeight: 56,
        alignItems: 'center',
        gap: GeneralStyle.spacing.sm,
        paddingHorizontal: GeneralStyle.spacing.sm,
        borderRadius: GeneralStyle.radius.md,
        borderWidth: 1,
        borderColor: Colors.transparent,
    },
    drawerItemRtl: {
        flexDirection: 'row-reverse',
    },
    drawerItemLtr: {
        flexDirection: 'row',
    },
    drawerItemActive: {
        backgroundColor: Colors.navyTint,
        borderColor: Colors.borderSoft,
    },
    drawerItemIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.borderSoft,
    },
    drawerItemIconActive: {
        backgroundColor: Colors.goldWash,
        borderColor: Colors.premiumLine,
    },
    drawerItemText: {
        ...FontsStyle.textDecoration,
        flex: 1,
        color: Colors.slate,
        fontSize: 16,
    },
    drawerItemTextActive: {
        color: Colors.darkGreen,
    },
    drawerTextRight: {
        textAlign: 'right',
    },
    drawerTextLeft: {
        textAlign: 'left',
    },
    logoutButton: {
        minHeight: 56,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: GeneralStyle.spacing.sm,
        paddingHorizontal: GeneralStyle.spacing.md,
        marginTop: GeneralStyle.spacing.lg,
        borderRadius: GeneralStyle.radius.lg,
        borderWidth: 1,
        borderColor: Colors.premiumLine,
        backgroundColor: Colors.navyDeep,
        shadowColor: Colors.darkGreen,
        shadowOpacity: 0.12,
        shadowRadius: 10,
        shadowOffset: {width: 0, height: 5},
        elevation: 3,
    },
    logoutIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.surfaceElevated,
        borderWidth: 1,
        borderColor: Colors.color1Light,
    },
    logoutText: {
        ...FontsStyle.textDecoration,
        color: Colors.white,
        fontSize: 16,
    },
});
