import {StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import {FontsStyle} from '../../utils/FontsStyle';
import GeneralStyle from '../../utils/GeneralStyle';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
  },
  wizardContainer: {
    borderBottomWidth: 1,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingTop: GeneralStyle.spacing.md,
    paddingBottom: GeneralStyle.spacing.sm,
    backgroundColor: Colors.ivory,
    borderBottomColor: Colors.borderSoft,
    ...Colors.Shadow,
  },
  headerTopRow: {
    justifyContent: "space-between",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: GeneralStyle.spacing.sm,
  },
  containerDynamicComp: {
    flex: 1,
    minHeight: 0,
    backgroundColor: Colors.transparent,
  },
  errorContainer: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingTop: GeneralStyle.spacing.sm,
  },
  relationshipOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    backgroundColor: Colors.overlay,
  },
  relationshipModal: {
    width: '100%',
    maxWidth: 360,
    padding: GeneralStyle.spacing.lg,
    borderRadius: GeneralStyle.radius.lg,
    backgroundColor: Colors.surfaceElevated,
    borderTopWidth: 1,
    borderTopColor: Colors.premiumLine,
    borderLeftWidth: 1,
    borderLeftColor: Colors.borderSoft,
    ...Colors.Shadow,
    elevation: 8,
  },
  relationshipFloatingButton: {
    position: 'absolute',
    left: GeneralStyle.spacing.lg,
    bottom: GeneralStyle.spacing.xl,
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 27,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.surfaceElevated,
    ...Colors.Shadow,
    elevation: 8,
    zIndex: 20,
  },
  relationshipFloatingImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  relationshipFloatingButtonActive: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.goldWash,
  },
  relationshipFloatingDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.goldDark,
  },
  relationshipHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: GeneralStyle.spacing.md,
    gap: GeneralStyle.spacing.sm,
  },
  relationshipTitleBlock: {
    flex: 1,
    alignItems: 'flex-end',
  },
  relationshipTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: 22,
  },
  relationshipSubtitle: {
    ...FontsStyle.text,
    color: Colors.goldDark,
    marginTop: 2,
  },
  relationshipCloseButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.ivory,
  },
  relationshipCloseText: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    fontSize: 22,
    lineHeight: 24,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  rowReverse: {
    flexDirection: 'row-reverse',
  },
  statusOptions: {
    gap: GeneralStyle.spacing.xs,
    marginBottom: GeneralStyle.spacing.md,
  },
  statusOption: {
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
    borderLeftWidth: 3,
    borderLeftColor: Colors.borderSoft,
  },
  statusOptionActive: {
    backgroundColor: Colors.goldWash,
    borderColor: Colors.premiumLine,
    borderLeftColor: Colors.premiumLine,
  },
  statusOptionText: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    textAlign: 'center',
  },
  statusOptionTextActive: {
    color: Colors.darkGreen,
  },
  disabledOption: {
    opacity: 0.75,
  },
  relationshipActions: {
    gap: GeneralStyle.spacing.sm,
    marginTop: GeneralStyle.spacing.lg,
  },
  relationshipActionButton: {
    flex: 1,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
  },
  cancelButton: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.surfaceElevated,
  },
  saveButton: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.navyDeep,
  },
  relationshipActionText: {
    ...FontsStyle.textDecoration,
    color: Colors.darkGreen,
    fontSize: 16,
    textAlign: 'center',
  },
  saveButtonText: {
    color: Colors.white,
  },
  partnerSearchContainer: {
    gap: GeneralStyle.spacing.xs,
  },
  partnerSearchLabel: {
    ...FontsStyle.textDecoration,
    color: Colors.darkGreen,
    fontSize: 15,
  },
  partnerSearchInput: {
    ...FontsStyle.text,
    minHeight: 52,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    color: Colors.black,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  readOnlyInput: {
    backgroundColor: Colors.surfaceMuted,
    color: Colors.slate,
  },
  suggestionsPanel: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.ivory,
  },
  suggestionItem: {
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.line,
  },
  suggestionText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  emptySuggestion: {
    ...FontsStyle.text,
    color: Colors.slate,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
  },
  textRight: {
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  textLeft: {
    textAlign: 'left',
    writingDirection: 'ltr',
  },
  btn: {
    minWidth: 76,
    minHeight: 44,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.ivory,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    borderBottomColor: Colors.color1Light,
    shadowOpacity: 0,
    elevation: 0,
  },
  btnPlaceholder: {
    minWidth: 76,
  },
  primaryBtn: {
    backgroundColor: Colors.navyDeep,
    borderColor: Colors.premiumLine,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.sm,
  },
  title: {
    ...FontsStyle.wizardTitle,
    color: Colors.darkGreen,
    fontSize: 24,
    textAlign: 'center',
  },
  stepCaption: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 2,
  },
  btnText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  primaryBtnText: {
    color: Colors.white,
  },
  progressTrack: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    marginTop: GeneralStyle.spacing.sm,
  },
  progressDot: {
    width: 38,
    height: 4,
    borderRadius: 999,
    backgroundColor: Colors.line,
  },
  progressDotActive: {
    backgroundColor: Colors.premiumLine,
  },
});
