import {StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import {FontSize, FontsStyle} from '../../utils/FontsStyle';
import GeneralStyle from '../../utils/GeneralStyle';
import SharedStyles from '../../utils/SharedStyles';

export const styles = StyleSheet.create({
  ...SharedStyles,
  commitmentGateScreen: {
    flex: 1,
    backgroundColor: Colors.ivory,
  },
  commitmentOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.md,
    backgroundColor: Colors.overlay,
  },
  commitmentModal: {
    width: '100%',
    maxWidth: 390,
    padding: GeneralStyle.spacing.lg,
    borderRadius: GeneralStyle.radius.lg,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.white,
    ...Colors.Shadow,
    elevation: 10,
  },
  registrationModeModal: {
    width: '100%',
    maxWidth: 390,
    padding: GeneralStyle.spacing.lg,
    borderWidth: 2,
    borderColor: Colors.info,
    borderRadius: GeneralStyle.radius.lg,
    backgroundColor: Colors.white,
    ...Colors.Shadow,
    elevation: 10,
  },
  registrationModeClose: {
    alignSelf: 'flex-start',
  },
  registrationModeIconWrap: {
    width: GeneralStyle.size.badge,
    height: GeneralStyle.size.badge,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: GeneralStyle.spacing.sm,
    marginBottom: GeneralStyle.spacing.md,
    borderWidth: 2,
    borderColor: Colors.info,
    borderRadius: GeneralStyle.size.badge / 2,
    backgroundColor: Colors.softBlue,
  },
  registrationModeTitle: {
    ...FontsStyle.wizardTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'center',
  },
  registrationModeDescription: {
    ...FontsStyle.text,
    color: Colors.slate,
    marginTop: GeneralStyle.spacing.sm,
    textAlign: 'center',
  },
  registrationModeActions: {
    gap: GeneralStyle.spacing.sm,
    marginTop: GeneralStyle.spacing.lg,
  },
  registrationModeButton: {
    flex: 1,
    minHeight: GeneralStyle.size.action,
  },
  commitmentTitle: {
    ...FontsStyle.menuTitle,
    flex: 1,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'center',
  },
  commitmentHeader: {
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  commitmentIntro: {
    ...FontsStyle.text,
    color: Colors.slate,
    marginTop: GeneralStyle.spacing.sm,
  },
  commitmentItems: {
    gap: GeneralStyle.spacing.md,
    marginVertical: GeneralStyle.spacing.lg,
  },
  commitmentItem: {
    alignItems: 'flex-start',
    gap: GeneralStyle.spacing.sm,
  },
  commitmentCheck: {
    width: GeneralStyle.size.iconXs,
    color: Colors.goldDark,
    fontSize: FontSize.title,
    fontWeight: '700',
    textAlign: 'center',
  },
  commitmentItemText: {
    ...FontsStyle.text,
    flex: 1,
    color: Colors.darkGreen,
    lineHeight: 24,
  },
  commitmentAcceptButton: {
    minHeight: GeneralStyle.size.action,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.navyDeep,
  },
  commitmentAcceptText: {
    ...FontsStyle.textDecoration,
    color: Colors.white,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  commitmentDeclineButton: {
    minHeight: GeneralStyle.size.field,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: GeneralStyle.spacing.sm,
  },
  commitmentDeclineText: {
    ...FontsStyle.text,
    color: Colors.slate,
    textAlign: 'center',
  },
  container: {
    flex: 1,
    width: '100%',
  },
  wizardContainer: {
    borderBottomWidth: 1,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingTop: GeneralStyle.spacing.md,
    paddingBottom: GeneralStyle.spacing.sm,
    backgroundColor: Colors.ivory,
    borderBottomColor: Colors.borderSoft,
    ...Colors.Shadow,
  },
  headerTopRow: {
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: GeneralStyle.spacing.sm,
  },
  containerDynamicComp: {
    flex: 1,
    minHeight: 0,
    backgroundColor: Colors.transparent,
  },
  errorContainer: {
    paddingHorizontal: GeneralStyle.spacing.sm,
    paddingTop: GeneralStyle.spacing.sm,
  },
  formExitButton: {
    minWidth: GeneralStyle.size.avatarSmall,
    minHeight: GeneralStyle.size.control,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    borderColor: Colors.danger,
    backgroundColor: Colors.dangerSoft,
  },
  formExitButtonText: {
    ...FontsStyle.textDecoration,
    color: Colors.danger,
  },
  relationshipOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.lg,
    backgroundColor: Colors.overlay,
  },
  relationshipModal: {
    width: '100%',
    maxWidth: GeneralStyle.size.modal,
    padding: GeneralStyle.spacing.md,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
  },
  relationshipFloatingButton: {
    position: 'absolute',
    left: GeneralStyle.spacing.lg,
    bottom: GeneralStyle.spacing.xl,
    width: GeneralStyle.size.action,
    height: GeneralStyle.size.action,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 27,
    borderWidth: 1,
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.navyDeep,
    overflow: 'hidden',
    ...Colors.Shadow,
    elevation: 8,
    zIndex: 20,
  },
  relationshipFloatingImage: {
    width: GeneralStyle.size.action,
    height: GeneralStyle.size.action,
    borderRadius: 27,
    resizeMode: 'cover',
  },
  relationshipFloatingButtonActive: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.navyDeep,
  },
  relationshipFloatingDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.goldDark,
  },
  relationshipHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: GeneralStyle.spacing.sm,
    gap: GeneralStyle.spacing.sm,
  },
  relationshipTitleBlock: {
    flex: 1,
    alignItems: 'flex-end',
  },
  relationshipTitle: {
    ...FontsStyle.menuTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.heading,
  },
  relationshipCloseButton: {
    width: GeneralStyle.size.icon,
    height: GeneralStyle.size.icon,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.sm,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    backgroundColor: Colors.ivory,
  },
  relationshipCloseText: {
    ...SharedStyles.iconGlyphText,
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
  },
  statusOptions: {
    alignItems: 'stretch',
    gap: GeneralStyle.spacing.xs,
    marginBottom: GeneralStyle.spacing.sm,
  },
  statusOption: {
    flex: 1,
    minHeight: GeneralStyle.size.field,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
  },
  statusOptionActive: {
    backgroundColor: Colors.goldWash,
    borderColor: Colors.premiumLine,
  },
  statusOptionText: {
    ...FontsStyle.subTitle,
    color: Colors.darkGreen,
    textAlign: 'center',
  },
  statusOptionTextActive: {
    color: Colors.darkGreen,
  },
  disabledOption: {
    opacity: 0.75,
  },
  relationshipActions: {
    gap: GeneralStyle.spacing.sm,
    marginTop: GeneralStyle.spacing.md,
  },
  relationshipActionButton: {
    flex: 1,
    minHeight: GeneralStyle.size.action,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: GeneralStyle.radius.md,
    borderWidth: 1,
  },
  cancelButton: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.white,
  },
  saveButton: {
    borderColor: Colors.premiumLine,
    backgroundColor: Colors.navyDeep,
  },
  relationshipActionText: {
    ...FontsStyle.textDecoration,
    color: Colors.darkGreen,
    fontSize: FontSize.body,
    textAlign: 'center',
  },
  saveButtonText: {
    color: Colors.white,
  },
  partnerSearchContainer: {
    gap: GeneralStyle.spacing.sm,
    paddingTop: GeneralStyle.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.line,
  },
  partnerSearchLabel: {
    ...FontsStyle.textDecoration,
    color: Colors.darkGreen,
    fontSize: FontSize.small,
  },
  partnerSearchInput: {
    ...FontsStyle.text,
    minHeight: GeneralStyle.size.control,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    color: Colors.black,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.white,
  },
  readOnlyInput: {
    backgroundColor: Colors.surfaceMuted,
    color: Colors.slate,
  },
  suggestionsPanel: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    backgroundColor: Colors.ivory,
  },
  suggestionItem: {
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.line,
  },
  suggestionText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  emptySuggestion: {
    ...FontsStyle.text,
    color: Colors.slate,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
  },
  btn: {
    minWidth: GeneralStyle.size.avatarSmall,
    minHeight: GeneralStyle.size.control,
    paddingHorizontal: GeneralStyle.spacing.md,
    paddingVertical: GeneralStyle.spacing.sm,
    backgroundColor: Colors.ivory,
    borderColor: Colors.borderSoft,
    borderRadius: GeneralStyle.radius.md,
    borderBottomColor: Colors.color1Light,
    shadowOpacity: 0,
    elevation: 0,
  },
  btnPlaceholder: {
    minWidth: GeneralStyle.size.avatarSmall,
  },
  primaryBtn: {
    backgroundColor: Colors.navyDeep,
    borderColor: Colors.premiumLine,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: GeneralStyle.spacing.sm,
  },
  title: {
    ...FontsStyle.wizardTitle,
    color: Colors.darkGreen,
    fontSize: FontSize.section,
    textAlign: 'center',
  },
  stepCaption: {
    ...FontsStyle.text,
    color: Colors.slate,
    fontSize: FontSize.caption,
    textAlign: 'center',
    marginTop: 2,
  },
  btnText: {
    ...FontsStyle.text,
    color: Colors.darkGreen,
  },
  primaryBtnText: {
    color: Colors.white,
  },
  progressTrack: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: GeneralStyle.spacing.xs,
    marginTop: GeneralStyle.spacing.sm,
  },
  progressDot: {
    width: GeneralStyle.size.iconLarge,
    height: 4,
    borderRadius: 999,
    backgroundColor: Colors.line,
  },
  progressDotActive: {
    backgroundColor: Colors.premiumLine,
  },
});
