export type MatchCardType = {
  name: string;
  age: number;
  height: string;
  status: string;
  images: string[];
  numOfChildren: number;
  gender: string;
  offered?: boolean;
  met?: boolean;
  meetingStatus?: 'available' | 'busy';
  meetingDate?: string;
  meetingTime?: string;
  meetingLocation?: string;
  isShowInfoButtons?: boolean;
  isShowMeetingInfo?: boolean;
  isSlide?: boolean;
  mail?: string;
  phone: string;
  matcherPhone: string;
  matcherMail?: string;
  matcherName?: string;
  isShowMoreInfo?: boolean;
  isImagePreviewEnabled?: boolean;
  relationshipStatus?: 'engaged' | 'married';
  partnerName?: string;
  partnerImage?: string;
  city?: string;
};
