# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

target 'TheMatchers' do
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        header_search_paths = build_config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        react_native_dependencies_headers = '"$(PODS_ROOT)/ReactNativeDependencies/framework/packages/react-native/ReactNativeDependencies.xcframework/Headers"'
        header_search_paths << react_native_dependencies_headers unless header_search_paths.include?(react_native_dependencies_headers)
        if target.name == 'RNNotifee'
          [
            '"$(PODS_ROOT)/Headers/Private/React-Core"',
            '"$(PODS_ROOT)/Headers/Public/React-Core-prebuilt/React_Core"',
          ].each do |path|
            header_search_paths << path unless header_search_paths.include?(path)
          end
        end
        if target.name == 'RNFBMessaging'
          build_config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        end
      end
    end
  end
end
