import {FormField} from './FormFields.type';
import {cityOptions} from './cityOptions';
import {getDateBefore} from './generalFunction';

const detailsFormArray: FormField[] = [
  // personalDetails
  {
    id: 'fullName',
    text: 'fullNameLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'personalDetails',
  },
  {
    id: 'gender',
    text: 'genderLabel',
    options: [
      {id: 1, name: 'gender', label: 'male'},
      {id: 2, name: 'gender', label: 'female'},
    ],
    fieldType: 'radioButton',
    handlePress: () => {},
    collapseTitle: 'personalDetails',
  },
  {
    id: 'birthDate',
    text: 'birthDateGregorianLabel',
    fieldType: 'datePicker',
    maxDate: getDateBefore(18),
    collapseTitle: 'personalDetails',
  },
  {
    id: 'birthDateHe',
    text: 'birthDateHebrewLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    isEditable: false,
    collapseTitle: 'personalDetails',
  },
  {
    id: 'age',
    text: 'ageLabel',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    isEditable: false,
    collapseTitle: 'personalDetails',
  },
  {
    id: 'hight',
    text: 'heightLabel',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    collapseTitle: 'personalDetails',
  },
  {
    id: 'city',
    text: 'cityLabel',
    fieldType: 'autocomplete',
    options: cityOptions,
    autocompleteSource: 'israelCities',
    collapseTitle: 'personalDetails',
  },
  {
    id: 'status',
    text: 'statusLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'status', label: 'singleStatus'},
      {id: 2, name: 'status', label: 'widowedStatus'},
      {id: 3, name: 'status', label: 'divorcedStatus'},
      {id: 4, name: 'status', label: 'widowedWithChildrenStatus'},
      {id: 5, name: 'status', label: 'divorcedWithChildrenStatus'},
    ],
    collapseTitle: 'personalDetails',
  },
  {
    id: 'countOfChildren',
    text: 'childrenCountLabel',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    condition: [
      {fieldId: 'status', value: '4'},
      {fieldId: 'status', value: '5'},
    ],
    collapseTitle: 'personalDetails',
  },
  {
    id: 'hasChildCustody',
    text: 'childCustodyQuestion',
    fieldType: 'switch',
    condition: [{fieldId: 'status', value: '5'}],
    collapseTitle: 'personalDetails',
  },
  {
    id: 'childCustody',
    text: 'childCustodyDetailsLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [{fieldId: 'hasChildCustody', value: 'true'}],
    collapseTitle: 'personalDetails',
  },
  {
    id: 'typeOfHeadCover',
    text: 'headCoverLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {
        id: 1,
        name: 'typeOfHeadCover',
        label: 'blackKippah',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {
        id: 2,
        name: 'typeOfHeadCover',
        label: 'knittedKippah',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {
        id: 3,
        name: 'typeOfHeadCover',
        label: 'scarf',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
      {
        id: 4,
        name: 'typeOfHeadCover',
        label: 'wig',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
      {
        id: 5,
        name: 'typeOfHeadCover',
        label: 'scarfAndWig',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
    ],
    collapseTitle: 'personalDetails',
  },

  // contactDetails
  {
    id: 'phone',
    text: 'phoneLabel',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    collapseTitle: 'contactDetails',
    maxLength: 10,
  },
  {
    id: 'typeOfPhone',
    text: 'phoneTypeLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'typeOfPhone', label: 'kosherPhone'},
      {id: 2, name: 'typeOfPhone', label: 'protectedPhone'},
      {id: 3, name: 'typeOfPhone', label: 'unprotectedPhone'},
    ],
    collapseTitle: 'contactDetails',
  },
  {
    id: 'mail',
    text: 'emailLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'contactDetails',
  },

  // styleSection
  {
    id: 'hashkafa',
    text: 'worldviewLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'hashkafa', label: 'religiousStatus'},
      {id: 2, name: 'hashkafa', label: 'harediStatus'},
      {id: 3, name: 'hashkafa', label: 'modernHarediStatus'},
      {id: 4, name: 'hashkafa', label: 'baalTeshuvaStatus'},
    ],
    collapseTitle: 'styleSection',
  },
  {
    id: 'hozerBitshoveAge',
    text: 'baalTeshuvaAgeQuestion',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    condition: [{fieldId: 'hashkafa', value: '4'}],
    collapseTitle: 'styleSection',
  },
  {
    id: 'isGer',
    text: 'convertQuestion',
    fieldType: 'switch',
    collapseTitle: 'styleSection',
  },

  // generalDetails
  {
    id: 'isStayInCurrentLocation',
    text: 'stayInCurrentCityQuestion',
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'isSmoker',
    text: 'smokerQuestion',
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'isHasDrivingLicense',
    text: 'drivingLicenseQuestion',
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'isCohen',
    text: 'cohenQuestion',
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'isVaccinatedCorona',
    text: 'covidVaccinatedQuestion',
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'zerem',
    text: 'communityLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'zerem', label: 'hasidic'},
      {id: 2, name: 'zerem', label: 'litvish'},
      {id: 3, name: 'zerem', label: 'sephardicCommunity'},
    ],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'hasidut',
    text: 'hasidicGroupQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [{fieldId: 'zerem', value: '1'}],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'tribe',
    text: 'ethnicCommunityQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [{fieldId: 'zerem', value: '3'}],
    collapseTitle: 'generalDetails',
  },

  // workAndEducation
  {
    id: 'highSchoolName',
    text: 'highSchoolNameLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [{fieldId: 'gender', value: '2'}],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'seminarName',
    text: 'seminaryNameLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [{fieldId: 'gender', value: '2'}],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'whatWorks',
    text: 'occupation',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {
        id: 1,
        name: 'whatWorks',
        label: 'yeshivaStudent',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {
        id: 2,
        name: 'whatWorks',
        label: 'kollelStudent',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {id: 3, name: 'whatWorks', label: 'working'},
      {id: 4, name: 'whatWorks', label: 'academicStudent'},
      {id: 5, name: 'whatWorks', label: 'workingAndStudyingAcademic'},
      {
        id: 6,
        name: 'whatWorks',
        label: 'workingAndLearning',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {
        id: 7,
        name: 'whatWorks',
        label: 'army',
        isShow: [{fieldId: 'gender', value: '1'}],
      },
      {
        id: 8,
        name: 'whatWorks',
        label: 'nationalService',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'isServedInArmy',
    text: 'servedArmyQuestion',
    fieldType: 'switch',
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'isNationalService',
    text: 'nationalServiceQuestion',
    fieldType: 'switch',
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'smallYeshiva',
    text: 'yeshivaKetanaLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '1'},
      {fieldId: 'gender', value: '1'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'BigYeshiva',
    text: 'yeshivaGedolaLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '1'},
      {fieldId: 'gender', value: '1'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'kibutz',
    text: 'kibbutzLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '1'},
      {fieldId: 'gender', value: '1'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'colel',
    text: 'kollelLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '2'},
      {fieldId: 'gender', value: '1'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'nameOfWork',
    text: 'workDetailsQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '3'},
      {fieldId: 'whatWorks', value: '5'},
      {fieldId: 'whatWorks', value: '6'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'whatLearning',
    text: 'studyDetailsQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    condition: [
      {fieldId: 'whatWorks', value: '4'},
      {fieldId: 'whatWorks', value: '5'},
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'education',
    text: 'educationLabel',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'education', label: 'degree'},
      {id: 2, name: 'education', label: 'practicalEngineer'},
      {id: 3, name: 'education', label: 'matriculation'},
      {
        id: 4,
        name: 'education',
        label: 'yeshivaEducation',
        isShow: [
          {fieldId: 'gender', value: '1'},
          {fieldId: 'whatWorks', value: '1'},
        ],
      },
      {id: 5, name: 'education', label: 'twelveYearsSchooling'},
    ],
    collapseTitle: 'workAndEducation',
  },

  // appearance
  {
    id: 'bodyStructure',
    text: 'bodyTypeLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'bodyStructure', label: 'slim'},
      {id: 2, name: 'bodyStructure', label: 'averageBody'},
      {id: 3, name: 'bodyStructure', label: 'fullFigured'},
    ],
    collapseTitle: 'appearance',
  },
  {
    id: 'skinColor',
    text: 'skinToneLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'skinColor', label: 'lightSkin'},
      {id: 2, name: 'skinColor', label: 'mediumSkin'},
      {id: 3, name: 'skinColor', label: 'darkSkin'},
    ],
    collapseTitle: 'appearance',
  },
  {
    id: 'beardType',
    text: 'beardTypeLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'beardType', label: 'naturalBeard'},
      {id: 2, name: 'beardType', label: 'trimmedBeard'},
      {id: 3, name: 'beardType', label: 'stubble'},
      {id: 4, name: 'beardType', label: 'cleanShaven'},
    ],
    condition: [{fieldId: 'gender', value: '1'}],
    collapseTitle: 'appearance',
  },
  {
    id: 'clothes',
    text: 'dressStyleLabel',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'clothes', label: 'blackWhiteDress'},
      {id: 2, name: 'clothes', label: 'colorfulDress'},
      {id: 3, name: 'clothes', label: 'colorfulWeekdayBlackWhiteShabbat'},
    ],
    condition: [{fieldId: 'gender', value: '1'}],
    collapseTitle: 'appearance',
  },

  // additionalDetails
  {
    id: 'fatherName',
    text: 'fatherNameLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'motherName',
    text: 'motherNameLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'rabbiName',
    text: 'rabbiNameQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'rabbiPhone',
    text: 'rabbiPhoneNumber',
    keyboardTypeOption: 'numeric',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'importantInfo',
    text: 'aboutMePlaceholder',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    isMultiline: true,
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'familyInfo',
    text: 'aboutFamily',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    isMultiline: true,
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'phonesForInquiries',
    text: 'referencePhonesLabel',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    isMultiline: true,
    collapseTitle: 'additionalDetails',
  },
];

export default detailsFormArray;
