import {FormField} from './FormFields.type';

const matchFormArray: FormField[] = [
  {
    id: 'matchRangeAges',
    text: 'ageRange',
    fieldType: 'range',
    minRange: 18,
    maxRange: 90,
    step: 1,
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchCountOfChildren',
    text: 'maxChildren',
    fieldType: 'range',
    minRange: 0,
    maxRange: 10,
    step: 1,
    condition: [
      {fieldId: 'matchStatus', value: '4'},
      {fieldId: 'matchStatus', value: '5'},
    ],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchRangeHeights',
    text: 'heightRange',
    fieldType: 'range',
    minRange: 120,
    maxRange: 200,
    step: 1,
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchArea',
    text: 'partnerResidentialArea',
    genderTextLabels: {
      male: 'partnerResidentialAreaMale',
      female: 'partnerResidentialAreaFemale',
    },
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchArea', label: 'centralArea'},
      {id: 2, name: 'matchArea', label: 'southernArea'},
      {id: 3, name: 'matchArea', label: 'northernArea'},
      {id: 4, name: 'matchArea', label: 'jerusalemArea'},
      {id: 5, name: 'matchArea', label: 'shfelaArea'},
    ],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchTypeOfPhone',
    text: 'phoneTypeLabel',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchTypeOfPhone', label: 'kosherPhone'},
      {id: 2, name: 'matchTypeOfPhone', label: 'protectedPhone'},
      {id: 3, name: 'matchTypeOfPhone', label: 'unprotectedPhone'},
    ],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchStatus',
    text: 'status',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {
        id: 1,
        name: 'matchStatus',
        label: 'single',
        genderLabels: {
          male: 'singleStatusMale',
          female: 'singleStatusFemale',
        },
      },
      {
        id: 2,
        name: 'matchStatus',
        label: 'widower',
        genderLabels: {
          male: 'widowedStatusMale',
          female: 'widowedStatusFemale',
        },
      },
      {
        id: 3,
        name: 'matchStatus',
        label: 'divorced',
        genderLabels: {
          male: 'divorcedStatusMale',
          female: 'divorcedStatusFemale',
        },
        hideWhen: [
          {fieldId: 'gender', value: '1'},
          {fieldId: 'isCohen', value: 'true'},
        ],
      },
      {
        id: 4,
        name: 'matchStatus',
        label: 'widowerWithChildren',
        genderLabels: {
          male: 'widowedWithChildrenStatusMale',
          female: 'widowedWithChildrenStatusFemale',
        },
      },
      {
        id: 5,
        name: 'matchStatus',
        label: 'divorcedWithChildren',
        genderLabels: {
          male: 'divorcedWithChildrenStatusMale',
          female: 'divorcedWithChildrenStatusFemale',
        },
        hideWhen: [
          {fieldId: 'gender', value: '1'},
          {fieldId: 'isCohen', value: 'true'},
        ],
      },
    ],
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchHashkafa',
    text: 'worldview',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {
        id: 1,
        name: 'matchHashkafa',
        label: 'religious',
        genderLabels: {
          male: 'religiousStatusMale',
          female: 'religiousStatusFemale',
        },
      },
      {
        id: 5,
        name: 'matchHashkafa',
        label: 'datiLeumi',
        genderLabels: {
          male: 'datiLeumiStatusMale',
          female: 'datiLeumiStatusFemale',
        },
      },
      {
        id: 2,
        name: 'matchHashkafa',
        label: 'haredi',
        genderLabels: {
          male: 'harediStatusMale',
          female: 'harediStatusFemale',
        },
      },
      {
        id: 3,
        name: 'matchHashkafa',
        label: 'modernHaredi',
        genderLabels: {
          male: 'modernHarediStatusMale',
          female: 'modernHarediStatusFemale',
        },
      },
      {
        id: 4,
        name: 'matchHashkafa',
        label: 'baalTeshuva',
        genderLabels: {
          male: 'baalTeshuvaStatusMale',
          female: 'baalTeshuvaStatusFemale',
        },
      },
    ],
    collapseTitle: 'styleSection',
  },
  {
    id: 'matchIsWantSmoker',
    text: 'openToSmokerQuestion',
    genderTextLabels: {
      male: 'openToSmokerQuestionMale',
      female: 'openToSmokerQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsWantCohen',
    text: 'openToCohenQuestion',
    genderTextLabels: {
      male: 'openToCohenQuestionMale',
      female: 'openToCohenQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsGer',
    text: 'openToConvertQuestion',
    genderTextLabels: {
      male: 'openToConvertQuestionMale',
      female: 'openToConvertQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsHozerBitshuva',
    text: 'openToBaalTeshuvaQuestion',
    genderTextLabels: {
      male: 'openToBaalTeshuvaQuestionMale',
      female: 'openToBaalTeshuvaQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsVaccinatedCorona',
    text: 'openToCovidVaccinatedQuestion',
    genderTextLabels: {
      male: 'openToCovidVaccinatedQuestionMale',
      female: 'openToCovidVaccinatedQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsWantNationalService',
    text: 'openToNationalServiceQuestion',
    genderTextLabels: {
      male: 'openToNationalServiceQuestionMale',
      female: 'openToNationalServiceQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsWantArmy',
    text: 'openToArmyServiceQuestion',
    genderTextLabels: {
      male: 'openToArmyServiceQuestionMale',
      female: 'openToArmyServiceQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsWantOrphan',
    text: 'openToOrphanQuestion',
    genderTextLabels: {
      male: 'openToOrphanQuestionMale',
      female: 'openToOrphanQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsWantDivorcedParents',
    text: 'openToDivorcedParentsQuestion',
    genderTextLabels: {
      male: 'openToDivorcedParentsQuestionMale',
      female: 'openToDivorcedParentsQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchIsDrivingLicense',
    text: 'openToDrivingLicenseQuestion',
    genderTextLabels: {
      male: 'openToDrivingLicenseQuestionMale',
      female: 'openToDrivingLicenseQuestionFemale',
    },
    fieldType: 'switch',
    collapseTitle: 'generalDetails',
  },
  {
    id: 'matchWhatWorks',
    text: 'occupation',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {
        id: 1,
        name: 'matchWhatWorks',
        label: 'yeshivaStudent',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
      {
        id: 2,
        name: 'matchWhatWorks',
        label: 'kollelStudent',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
      {id: 3, name: 'matchWhatWorks', label: 'working'},
      {id: 4, name: 'matchWhatWorks', label: 'academicStudent'},
      {id: 5, name: 'matchWhatWorks', label: 'workingAndStudyingAcademic'},
      {
        id: 6,
        name: 'matchWhatWorks',
        label: 'workingAndLearning',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'matchEducation',
    text: 'education',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchEducation', label: 'degree'},
      {id: 2, name: 'matchEducation', label: 'practicalEngineer'},
      {id: 3, name: 'matchEducation', label: 'matriculation'},
      {
        id: 4,
        name: 'matchEducation',
        label: 'yeshivaEducation',
        isShow: [{fieldId: 'gender', value: '2'}],
      },
    ],
    collapseTitle: 'workAndEducation',
  },
  {
    id: 'matchBodyStructure',
    text: 'bodyType',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchBodyStructure', label: 'slim'},
      {id: 2, name: 'matchBodyStructure', label: 'averageBody'},
      {id: 3, name: 'matchBodyStructure', label: 'fullFigured'},
    ],
    collapseTitle: 'appearance',
  },
  {
    id: 'matchSkinColor',
    text: 'skinTone',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchSkinColor', label: 'lightSkin'},
      {id: 2, name: 'matchSkinColor', label: 'darkSkin'},
      {id: 3, name: 'matchSkinColor', label: 'noMatter'},
    ],
    collapseTitle: 'appearance',
  },
  {
    id: 'matchBeardType',
    text: 'beardType',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchBeardType', label: 'naturalBeard'},
      {id: 2, name: 'matchBeardType', label: 'trimmedBeard'},
      {id: 3, name: 'matchBeardType', label: 'stubble'},
      {id: 4, name: 'matchBeardType', label: 'cleanShaven'},
    ],
    collapseTitle: 'appearance',
    condition: [{fieldId: 'gender', value: '2'}],
  },
  {
    id: 'matchClothes',
    text: 'dressStyle',
    fieldType: 'checkbox',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchClothes', label: 'blackWhiteDress'},
      {id: 2, name: 'matchClothes', label: 'colorfulDress'},
      {id: 3, name: 'matchClothes', label: 'colorfulWeekdayBlackWhiteShabbat'},
    ],
    collapseTitle: 'appearance',
    condition: [{fieldId: 'gender', value: '2'}],
  },
  {
    id: 'matchZerem',
    text: 'community',
    fieldType: 'select',
    handlePress: () => console.log(),
    options: [
      {id: 1, name: 'matchZerem', label: 'hasidic'},
      {id: 2, name: 'matchZerem', label: 'litvish'},
      {id: 3, name: 'matchZerem', label: 'sephardic'},
    ],
    collapseTitle: 'additionalDetails',
  },
  {
    id: 'matchHasidut',
    text: 'hasidicGroupQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
    condition: [{fieldId: 'matchZerem', value: '1'}],
  },
  {
    id: 'matchTribe',
    text: 'preferredEthnicCommunityQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    collapseTitle: 'additionalDetails',
    condition: [{fieldId: 'matchZerem', value: '3'}],
  },
  {
    id: 'matchImportantInfo',
    text: 'importantInPartnerQuestion',
    keyboardTypeOption: 'default',
    fieldType: 'input',
    isMultiline: true,
    collapseTitle: 'additionalDetails',
  },
];

export default matchFormArray;
